### PR TITLE
674 currency symbol order fixes

### LINKED ISSUE #674: When no system language selected, add new card crashes
When having not the system language selected, the app crashes when trying to add a new card (either by scanning it or entering it manually)

System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime
- Catima 2.11.2 from F-Droid

### PR DESCRIPTION
**Pull request by Kethen**
#674 please review

### CODE REVIEW

**Review by Altonss — APPROVED** [review]
I have tested it and it solves the issue #674 on my Android 5.0.2 device. Thanks a lot for this fix!

File: app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java [hunk 1]
```diff
@@ -15,9 +16,13 @@
     SharedPreferences pref;
     HashMap<String, Integer> supportedThemes;
 
+    // store system locale for Build.VERSION.SDK_INT >= Build.VERSION_CODES.N
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java:19]: You say `>=` here, but in LoyaltyCardEditActivity this is used in the `<` version of the if loop. Should this comment be `<` instead of `>=`?

File: app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java [hunk 2]
```diff
@@ -15,9 +16,13 @@
...
+    protected Locale SYSTEM_LOCALE;
+
     @Override
     protected void attachBaseContext(Context base) {
         // Apply chosen language
+        SYSTEM_LOCALE = Locale.getDefault();
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java:25]: Why always save this for every activity when only used in the Edit activity?

**Review by TheLastProject — CHANGES_REQUESTED** [review]
