### PR TITLE
Fix active tab lost on rotation

### LINKED ISSUE #218: Active tab in edit view lost on rotation
Should remember the active tab when rotating instead of resetting to Card.

### PR DESCRIPTION
**Pull request by KevinSJ**
Fixes #218

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks for your contribution! After comparing with MainActivity I see the state is correctly kept on rotation there despite the lack of onSaveInstanceState and onRestoreInstanceState funcction. I need to see why it works without and what way is better. For consistency's sake it would be best to use one method everywhere at least.

**Comment by KevinSJ** [comment]
Hi @TheLastProject, I think it might be because of this line: https://github.com/TheLastProject/Catima/blob/d8d8a59707b9223753d5f6d04d5bfe4f4c38a258/app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java#L439

**Comment by TheLastProject** [comment]
I looked into that but that's not why it resets. The `selectTab` is to trigger the display-content-relevant-to-this-tab code.

I see now the reason the main activity work is because it is stored in a preference so it is actually stored even when you close and restart the app.

So your way in this PR does seem the way to go. I just need to test it a bit :)

File: app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java [hunk 1]
```diff
@@ -115,6 +117,20 @@ private void extractIntentFields(Intent intent)
...
 
+    @Override
+    public void onSaveInstanceState(@NonNull Bundle savedInstanceState) {
+        super.onSaveInstanceState(savedInstanceState);
+        tabs = findViewById(R.id.tabs);
+        savedInstanceState.putInt(STATE_TAB_INDEX, tabs.getSelectedTabPosition());
+    }
+
+    @Override
+    public void onRestoreInstanceState(@Nullable Bundle savedInstanceState) {
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:128]: This should be NonNull because Android documentation states it will never be called with null and to make spotBugs happy.

**Review by TheLastProject — CHANGES_REQUESTED** [review]

**Comment by TheLastProject** [comment]
Thanks!
